/av_vision_node:
    ros__parameters:
        ros_node:
            subs:
                camera_color: /robot/sensors/camera/color
                camera_depth: /robot/sensors/camera/depth
                camera_cloud: /robot/sensors/camera/cloud
                robot_pose: /robot/ekf/pose
            pubs:
                vision_target: /robot/vision/target
                vision_cloud: /robot/vision/cloud
                vision_goal: /robot/vision/goal
            thread_freq: 10.0
        follow:
            enable: true
            distance: 0.3 # [m]
        tracker:
            frame_width: 1280
            frame_height: 720
            enable_cuda: true
            yolo_input_width: 640
            yolo_input_height: 640
            yolo_model_path: install/av_navigation_ros/share/av_navigation_ros/yolo/yolo26m.onnx
            yolo_labels_path: install/av_navigation_ros/share/av_navigation_ros/yolo/coco.names
            yolo_search_classes: [2, 7]
            yolo_min_confidence: 0.5
            mean_circle_radius: 10 # [px]
            max_past_positions: 10
